export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_FAILURE = "FETCH_FAILURE";

export const GET_FETCH_SUCCESS = "GET_FETCH_SUCCESS";
export const POST_FETCH_SUCCESS = "POST_FETCH_SUCCESS";

export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const ADD_NEW_SALES = "ADD_NEW_SALES";
export const ADD_NEW_USERS = "ADD_NEW_USERS";
